version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - echo S3_DEPLOY_BUCKET_NAME=$S3_DEPLOY_BUCKET_NAME
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo DISTRIBUTION_ID=$DISTRIBUTION_ID
      - YEAR_MONTH=$(date +"%Y%m")
      - NOW=$YEAR_MONTH$(date +"%d")
      - FILENAME=archive_front_deploy_$now_$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
      - echo FILENAME=$FILENAME
  build:
    commands:
      - echo Build started on `date`
      - echo load env
      - aws s3 cp s3://$S3_LOTTO_DOTENV_BUCKET_NAME/front-test/.env.develop .env
      - cat .env
      - npm ci
      - npm run build
      - echo backup file
      - zip -r $FILENAME out/
      - aws s3 cp $FILENAME s3://$S3_DEPLOY_BUCKET_NAME/backup/$YEAR_MONTH/
      - echo deploy files
      - aws s3 sync out/ s3://$S3_DEPLOY_BUCKET_NAME  --exclude "backup*" --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID  --path "/*"