version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo =============================================================================
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - echo AWS_REGION=$AWS_REGION
      - echo CODEBUILD_BATCH_BUILD_IDENTIFIER=$CODEBUILD_BATCH_BUILD_IDENTIFIER
      - echo CODEBUILD_BUILD_ARN=$CODEBUILD_BUILD_ARN
      - echo CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID
      - echo CODEBUILD_BUILD_IMAGE=$CODEBUILD_BUILD_IMAGE
      - echo CODEBUILD_BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER
      - echo CODEBUILD_BUILD_SUCCEEDING=$CODEBUILD_BUILD_SUCCEEDING
      - echo CODEBUILD_INITIATOR=$CODEBUILD_INITIATOR
      - echo CODEBUILD_KMS_KEY_ID=$CODEBUILD_KMS_KEY_ID
      - echo CODEBUILD_LOG_PATH=$CODEBUILD_LOG_PATH
      - echo CODEBUILD_PUBLIC_BUILD_URL=$CODEBUILD_PUBLIC_BUILD_URL
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo CODEBUILD_SOURCE_REPO_URL=$CODEBUILD_SOURCE_REPO_URL
      - echo CODEBUILD_SOURCE_VERSION=$CODEBUILD_SOURCE_VERSION
      - echo CODEBUILD_SRC_DIR=$CODEBUILD_SRC_DIR
      - echo CODEBUILD_START_TIME=$CODEBUILD_START_TIME
      - echo CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID=$CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo CODEBUILD_WEBHOOK_BASE_REF=$CODEBUILD_WEBHOOK_BASE_REF
      - echo CODEBUILD_WEBHOOK_EVENT=$CODEBUILD_WEBHOOK_EVENT
      - echo CODEBUILD_WEBHOOK_MERGE_COMMIT=$CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo CODEBUILD_WEBHOOK_PREV_COMMIT=$CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo CODEBUILD_WEBHOOK_HEAD_REF=$CODEBUILD_WEBHOOK_HEAD_REF
      - echo CODEBUILD_WEBHOOK_TRIGGER=$CODEBUILD_WEBHOOK_TRIGGER
      - echo HOME=$HOME
      - echo =============================================================================
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - echo S3_DEPLOY_BUCKET_NAME=$S3_DEPLOY_BUCKET_NAME
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo DISTRIBUTION_ID=$DISTRIBUTION_ID
      - YEAR_MONTH=$(date +"%Y%m")
      - NOW=$YEAR_MONTH$(date +"%d")
      - FILENAME=archive_front_deploy_$now_$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
      - echo FILENAME=$FILENAME
  build:
    commands:
      - echo Build started on `date`
      - echo load env
      - aws s3 cp s3://$S3_LOTTO_DOTENV_BUCKET_NAME/front-test/.env.develop .env
      - cat .env
      - npm ci
      - npm run build
      - echo backup file
      - zip -r $FILENAME out/
      - aws s3 cp $FILENAME s3://$S3_DEPLOY_BUCKET_NAME/backup/$YEAR_MONTH/
      - echo deploy files
      - aws s3 sync out/ s3://$S3_DEPLOY_BUCKET_NAME  --exclude "backup*" --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID  --path "/*"